import 'package:get/get.dart';
class MyLocale implements Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    "ar" : {
     "0":"عربي",
      "1":"انكليزي",
      "2":"تسجيل دخول",
      "3": "سجل دخول لحسابك",
      "4":" رقم الموبايل" ,
      "5":"كلمة السر",
      "6":"اذا ليس لديك حساب ",
      "7":"اضغط هنا",
      "8":"الرقم غير صالح",
      "9":"موافق",
      "10":"خطأ",
      "11":"الرجاء تعبئة الحقول",
      "12":" !!! الرقم او كلمة السر غير صحيحة",
      "13":"تم انشاء الحساب مسبقا",
      "14":"انشاء حساب",
      "15":"سجل دخول في حسابك",
      "16":"اسم المستخدم",
      "17":"يجب ان لا تقل كلمة السر عن خمسة محارف",
      "18":"انشأ حساب",
      "19":" : الاعدادات",
      "20":"تسجيل خروج",
      "21":"الغاء",
      "22":"تسجيل خروج",
      "23":"هل تريد حقا تسجيل الخروج؟",
      "24":"الصفحة الرئيسية",
      "25":"المفضلة",
      "26":"السلة",
      "27":" ... ابحث عن الدواء",
      "28":"الادوية & الفيتامينات حسب التصنيفات",
      "29":"الوصف",
      "30":"السعر",
      "31":" : الاسم العلمي",
      "32":" : الشركة المصنعة ",
      "33":" : الكمية المتاحة ",
      "34":"اضف الى المفضلة",
      "35":"اضف الى السلة",
      "36":"ابحث عن تصنيف",
      "37":"مفضلتي",
      "38":" النتيجة ",
      "39":" : السعر الكلي",
      "40":"ادفع",
      "41":"سلتي",
      "42":": الكمية",
      "43":"تحديث الكمية",
      "44":"ادخل الكمية",
      "45":"لا يسمح بأكثر من 4 ارقام",
      "46":"طلباتي",
            "47":"الطلبات"


    },
    "en": {
      "0":"arabic",
      "1":"english",
      "2": "LOGIN",
      "3":"login to your account",
      "4":" user phone ",
      "5": "password",
      "6":"if you dont have account please  ",
      "7":"click here",
      "8":"The number is invalid ",
      "9":"Ok",
      "10":"Error",
      "11":"Please enter the faileds",
      "12":"phone or password is incorrect !!!",
      "13":"The account was previously created",
      "14":"REGISTER",
      "15":"register in your account",
      "16":" user name",
      "17":"Password should not be less than five characters",
      "18":"creat account ",
      "19":"Settings :",
      "20":"LOGOUT",
      "21":"Cancle",
      "22":"Logout",
      "23":"Do you really want to sign out?",
      "24":"HomePage",
      "25":"Favorite",
      "26":"Cart",
      "27":"search medicine ...",
      "28":"Medicine&Vitamins by Categories",
      "29":"Description",
      "30":"Price",
      "31":"Scientifice Name : ",
      "32":"The Manufacture Company : ",
      "33":"Quantity Available :",
      "34":"Add To Favoriet",
      "35":"Add To Cart",
      "36":"Search Category",
      "37":"My Favourite",
      "38":' the result ',
      "39":"Total Price : ",
      "40":"Pay",
      "41":"My Cart",
      "42":"Quantity :",
      "43":'Update Quantity',
      "44":"Enter quantity ",
      "45":"No more than 4 numbers are allowed",
      "46":"My Order",
      "47":"Order"

    



    }
  };
  
}